// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core_dart/firebase_core_dart.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBCL2IpyzzTDNno1PVBxki5AF_rUU6Gy5I",
      authDomain: "ud-ho-tro-cham-soc-cay.firebaseapp.com",
      projectId: "ud-ho-tro-cham-soc-cay",
      storageBucket: "ud-ho-tro-cham-soc-cay.appspot.com",
      messagingSenderId: "148854880609",
      appId: "1:148854880609:web:606d56fdc11a9375dead20"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCL2IpyzzTDNno1PVBxki5AF_rUU6Gy5I',
    appId: '1:148854880609:android:e8a5772c585f6e19dead20',
    messagingSenderId: '148854880609',
    projectId: 'ud-ho-tro-cham-soc-cay',
    storageBucket: 'ud-ho-tro-cham-soc-cay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCL2IpyzzTDNno1PVBxki5AF_rUU6Gy5I',
    appId: '1:148854880609:ios:99b115c9619b8ddadead20',
    messagingSenderId: '148854880609',
    projectId: 'ud-ho-tro-cham-soc-cay',
    storageBucket: 'ud-ho-tro-cham-soc-cay.appspot.com',
    iosClientId: '148854880609-tqs7vv1ch1bvrkel513ulgbs2u6a42st.apps.googleusercontent.com',
    iosBundleId: 'com.example.chamsoccaytrong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCL2IpyzzTDNno1PVBxki5AF_rUU6Gy5I',
    appId: '1:148854880609:ios:99b115c9619b8ddadead20',
    messagingSenderId: '148854880609',
    projectId: 'ud-ho-tro-cham-soc-cay',
    storageBucket: 'ud-ho-tro-cham-soc-cay.appspot.com',
    iosClientId: '148854880609-tqs7vv1ch1bvrkel513ulgbs2u6a42st.apps.googleusercontent.com',
    iosBundleId: 'com.example.chamsoccaytrong',
  );
}
